[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
url = "2.5.4"
serde_json = "1.0.137"
jsonschema = "0.28.2"
num_cpus = "1.0"
clap = { version = "4.5.26", features = ["derive"] }
num = "0.4.3"
